### PR TITLE
Speed up is_ancestor_of? and branch_contains?

### LINKED ISSUE #11: is_ancestor_of? is very slow to fail
The `GithubClient#is_ancestor_of?` method is very slow to fail on a repo with a lot of history. This is noticeable when a `check-recent-deploy` or `check-forward-deploy` check is going to fail - but it's OK and fast in the usual successful case.

Its purpose is to find whether commit X includes commit Y (the ancestor) in its history. It does this by loading commits from X and working backwards, looking for Y. In the normal case it's going to finish quickly as there are unlikely to have been many commits since the last deployment. In the negative case then it has to load every commit from X back to the root of the repo history.

It could be optimised to only look at commits within a certain timeframe, or only a certain number of commits (though it would be a problem after merging many new commits). It might also be possible to get a more direct answer from the GitHub API about whether two commits are related.

### PR DESCRIPTION
**Pull request by domcleal**
To check if one commit is an ancestor of another - or similarly whether
a commit is on a branch (in effect the same operation, just resolving
the branch name to its HEAD commit), GithubClient was iterating back
through commits from the candidate to see if the ancestor was in the
history.

This was usually fast if it was successful as we're normally deploying
only a few revisions on from the last deployment, so the ancestor (the
last deploy) is very close to the candidate commit. If the commit wasn't
an ancestor, then the commit history would keep being fetched until it
reached the root commit which could take a long time on a large repo.

Now the commit comparison is fetched from GitHub which provides the
merge base commit (see [git-merge-base(1)](https://git-scm.com/docs/git-merge-base)), making the result very easy
to determine as the merge base for two commits where one is the ancestor
of the other will always be the ancestor. If they're not directly
related, e.g. on a different branch, then the merge base will be a third
commit and so the check should fail.

This means the result can be computed with just two API calls and no
iteration over the commit history.

Fixes #11

### CODE REVIEW

File: lib/fa-harness-tools/github_client.rb [hunk 1]
```diff
@@ -91,14 +91,20 @@ def get_commit_sha_from_tag(tag)
     #
     # @return [Bool] True is <ancestor> is ancestor of <commit>
     def is_ancestor_of?(ancestor, commit)
-      !!find_commit(commit) { |c| c[:sha] == ancestor }
+      # Compare returns the merge base, the common point in history between the
+      # two commits. If X is the ancestor of Y, then the merge base must be X.
+      # If not, it's a different branch.
+      @octokit.compare(owner_repo, ancestor, commit)[:merge_base_commit][:sha] == get_commit_sha(ancestor)
```
Comment (evangeliakoleli) [inline lib/fa-harness-tools/github_client.rb:97]: Does this work when we are deploying the last known good SHA, with the assumption that every commit we are deploying is a merge commit?

Comment (domcleal) [reply lib/fa-harness-tools/github_client.rb:97]: Do you mean if `ancestor` and `commit` are the same, will it work (yes, it will)? Or something else?

**Review by evangeliakoleli — APPROVED** [review]
